#!/bin/bash
### BEGIN INIT INFO
# Provides:          haltusbpower
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Halts USB power...
### END INIT INFO
mkdir /dev/shm/comunix/
python2 /home/extend/server_tcp.py > /dev/null 2>&1 & disown
